### ISSUE TITLE
Duplicate symbols errors when installed through cocoa pods 

### ISSUE THREAD

**Issue by lopsae** [chute/photo-picker-plus-ios#77]
`GCConfiguration.{m,h}` and `GCConfigurationFile.{m,h}` are included in the project, which also exist in the Chute-SDK cocoapods. When building the app this causes duplicate symbols errors.

**Comment by LucasVanDongen** [comment]
Same here

**Comment by darko1002001** [comment]
This is still in development. there is an update being prepared around iOS 8 changes in a fork.
We will look into this issue as well.
This issue has been resolved and will be available with the update.

Issue will be closed when we publish it.

You can check it out in the form doing the pull request at this time as well.

**Comment by LucasVanDongen** [comment]
Pull request #78 ?

**Comment by darko1002001** [comment]
Yes correct.

**Comment by OliverDimitrov** [comment]
@LucasVanDongen ,
Can you try now? I believe that the problem is solved.

**Comment by LucasVanDongen** [comment]
I could compile it, so I think it's OK. It did conflict with another pod that already used AFNetworking 2.0

**Comment by OliverDimitrov** [comment]
Yes, unfortunately that still is an issue, but we're planning on changing that also. Although I'm not able to specify when this is going to happen.
